name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Tạo thư mục tạm và copy các file cần thiết
          mkdir deploy_hf
          cp -r tu-vi-app deploy_hf/
          cp Dockerfile deploy_hf/
          
          # 2. Khởi tạo Git và LFS trong thư mục tạm
          cd deploy_hf
          git init
          git branch -m main
          git lfs install
          git lfs track "*.png"
          git lfs track "*.jpg"
          git lfs track "*.svg"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy clean version to HF Space"
          
          # 3. Đẩy code lên Hugging Face (sử dụng Token trực tiếp)
          git push --force https://HuyRD2k:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/HuyRD2k/TuVi-App main
