name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Xóa thư mục Database
          rm -rf "1. Database"
          # Tạo một branch tạm thời (orphan) không có lịch sử để xóa sạch dấu vết file nặng
          git checkout --orphan hf-deploy
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy clean version to HF"
          git remote add space https://huggingface.co/spaces/HuyRD2k/TuVi-App
          git push --force space hf-deploy:main
